
CREATE TABLE public.courts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NOT NULL,
  full_name text NOT NULL
);

ALTER TABLE public.courts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own or admin all courts"
  ON public.courts FOR SELECT TO authenticated
  USING ((auth.uid() = user_id) OR has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Authenticated users can insert courts"
  ON public.courts FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Authenticated users can update courts"
  ON public.courts FOR UPDATE TO authenticated
  USING ((auth.uid() = user_id) OR has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Authenticated users can delete courts"
  ON public.courts FOR DELETE TO authenticated
  USING ((auth.uid() = user_id) OR has_role(auth.uid(), 'admin'::app_role));

ALTER TABLE public.sessions ADD COLUMN court_id integer REFERENCES public.courts(id);
